### ISSUE TITLE
更新服务器信息时若出现需要输入密码的情况会卡在输入密码的环节

### ISSUE THREAD

**Issue by cnstark** [cnstark/gputasker#7]

**Comment by 378978764** [comment]
更新服务器为什么会出现输入密码的环节？是密钥不能用了吗？

**Comment by cnstark** [comment]
> 更新服务器为什么会出现输入密码的环节？是密钥不能用了吗？

可能因为服务器故障或者刚重启还没有连接LDAP和NAS，思路是设置一个超时时间，避免一直等
